name: GitHub Metrics

on:
  schedule: [{ cron: "0 */12 * * *" }] # every 12 hours
  workflow_dispatch: # allow manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📊 Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Nairobi
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
