name: GitHub Metrics

on:
  schedule: [{ cron: "0 */12 * * *" }]  # Runs every 12 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📊 Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Nairobi
          plugin_languages: yes
          plugin_lines: yes
          plugin_repositories: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_traffic: yes
